### ISSUE TITLE
How to dynamically update template props content

### ISSUE THREAD

**Issue by ruslankonev** [QingWei-Li/vuep#13]
Hi! I want to change the template inside Vuep component dynamically. 
I was use Vuep `template` props with Vue v-bind method to local prop called `template` — `:template="template"`. But if I dynamic change the content of local template - Vuep component is not changes. How I can do that?

**Comment by ruslankonev** [comment]
First things I realize by the add a v-if condition for update component template. But now I has a
other things — how I can a get updated template from Vuep?

**Comment by ruslankonev** [comment]
Thanks for fix, but component still not work properly. If update template props - update only render ("Preview" component) but not Editor. And still I has a question — how I can get content from Editor, if I was update a code in Editor? Maybe add a "value" prop to Vuep? Then it was possible to use a `v-model` logic

**Comment by QingWei-Li** [comment]
@ruslankonev Sorry, I'm wrong.
I will add `value` prop. I reconsidered that I think `template` can not be changed when componente created, but we can dynamically update value through `value` prop(or `v-model`)
