### ISSUE TITLE
vuep can not compile such a template

### ISSUE THREAD

**Issue by jaweii** [QingWei-Li/vuep#16]
vuep can not compile such a template:

```
this.code = `
<template>
    <!-- ERROR:Unknown custom element: <my-global-component>  - did you register the component correctly?-->
     <my-global-component />
</template>
`
```
`<my-global-component/>`is a component of the UI framework

**Comment by Toilal** [comment]
I need to load into vuep a component that is available in my webpack bundle. Is it possible ?

**Comment by Toilal** [comment]
Hey @jaweii, I have implement a features that solve this issue : https://github.com/QingWei-Li/vuep/pull/23

**Comment by Toilal** [comment]
You still have to add a script tag to register the global component though.
